CREATE OR REPLACE PROCEDURE ALLCITYNETWORK_DEV.ON3_KIPI.POPULATE_COMBINED_TABLE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
-- INSERT INTO ONE TABLE FROM BASE 5 --
INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.COMBINED_BID_METRIC (
        DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
        organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
)
WITH bid_responses AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ADUNITCODE as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        null as state,
        null as rendered_bidder,
        ttl,
        sum(NO_BID_COUNT) as NO_BID,
        sum(BID_RESPONSE) as BID_RESPONSE,
        sum(CANCELLED_BIDS_COUNT) as CANCELLED_BIDS,
        sum(TIMED_OUT_BIDS_COUNT) as TIMED_OUT_BIDS,
        null as BID_REQUEST,    
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST,
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_RESPONSE_TEST_STR
    GROUP BY DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
bid_requests AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bidsource as bid_source,
        author,
        referrer,
        null as time_to_respond,
        null as state,
        null as cpm,
        null as rendered_bidder,
        null as ttl,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        sum(BID_REQUEST_COUNT) as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_REQUEST_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ads AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunit as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        author,
        referrer,
        cpm,
        rendered_bidder,
        null as time_to_respond,
        null as bidder,
        null as bid_source,
        null as ttl,
        state,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        sum(PAGE_VIEW_COUNT) as PAGE_VIEW,
        sum(IN_VIEW_IMPRESSION_COUNT) as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_ADS_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunit,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ad_response AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        ttl,
        time_to_respond,
        null as state,
        cpm,
        rendered_bidder,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_RESPONSE_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ad_request AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        cpm,
        time_to_respond,
        null as rendered_bidder,
        null as state,
        ttl,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        sum(AD_REQUEST_COUNT) as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_REQUEST_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
)
SELECT DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM bid_responses
UNION ALL
SELECT DERIVED_TSTAMP,
 COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM bid_requests
UNION ALL
SELECT DERIVED_TSTAMP,
COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ads
UNION ALL
SELECT DERIVED_TSTAMP,
COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ad_response
UNION ALL
SELECT DERIVED_TSTAMP,
 COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
       device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ad_request;
RETURN '' TABLE POPULATED SUCCESSFULY'';
END;

';