CREATE OR REPLACE PROCEDURE ALLCITYNETWORK_DEV.ON3_KIPI.POPULATE_EVENT_TABLES()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN

BEGIN TRANSACTION;
-- Insert into STG_ADS_TEST
INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.STG_ADS_TEST_METRIC (
   APP_ID,
	BR_COLORDEPTH,
	BR_COOKIES,
	BR_LANG,
	COLLECTOR_TSTAMP,
	DERIVED_TSTAMP,
	DOC_CHARSET,
	DOC_HEIGHT,
	DOC_WIDTH,
	DOMAIN_SESSIONID,
	DOMAIN_USERID,
	DVCE_CREATED_TSTAMP,
	DVCE_SCREENHEIGHT,
	DVCE_SCREENWIDTH,
	EVENT,
	EVENT_FINGERPRINT,
	EVENT_FORMAT,
	EVENT_ID,
	EVENT_NAME,
	EVENT_VENDOR,
	EVENT_VERSION,
	REFERRER,
	PAGE_URL,
	PAGE_URLHOST,
	PAGE_URLPATH,
	PAGE_URLPORT,
	PAGE_URLSCHEME,
	PLATFORM,
	USER_IPADDRESS,
	USERAGENT,
	V_COLLECTOR,
	V_ETL,
	V_TRACKER,
	AUTHOR,
	SESSION_DEPTH,
	SESSION_REFERRER,
	CITY,
	COUNTRY,
	SUBDIVISION_NAME,
	POSTAL_CODE,
	ISP,
	ORGANIZATION,
	CONNECTION_TYPE,
	DEVICE_FAMILY,
	OS_FAMILY,
	OS_VERSION,
	SNOWPLOW_WEB_PAGE_ID,
	DEVICE,
	ADNETWORKID,
	ADSERVER,
	ADSUBTYPE,
	ADTYPE,
	ADUNIT,
	AD_UNIT_PATH,
	ADVERTISERID,
	CAMPAIGNID,
	CPM,
	CREATIVEID,
	LINEITEMID,
	LOCATION,
	RAWADNETWORKID,
	RENDERED_ADOMAINS,
	RENDERED_BIDSOURCE,
	RENDERED_BIDDER,
	RENDERED_CPM,
	STATE,
    PAGE_VIEW_COUNT,
    IN_VIEW_IMPRESSION_COUNT
)
WITH flattened_data AS (
    SELECT
        events.VALUE:app_id::STRING AS app_id,
        events.VALUE:br_colordepth::STRING AS br_colordepth,
        events.VALUE:br_cookies::BOOLEAN AS br_cookies,
        events.VALUE:br_lang::STRING AS br_lang,
        events.VALUE:collector_tstamp::TIMESTAMP AS collector_tstamp,
        events.VALUE:derived_tstamp::TIMESTAMP AS derived_tstamp,
        events.VALUE:doc_charset::STRING AS doc_charset,
        events.VALUE:doc_height::INTEGER AS doc_height,
        events.VALUE:doc_width::INTEGER AS doc_width,
        events.VALUE:domain_sessionid::STRING AS domain_sessionid,
        events.VALUE:domain_userid::STRING AS domain_userid,
        events.VALUE:dvce_created_tstamp::TIMESTAMP AS dvce_created_tstamp,
        events.VALUE:dvce_screenheight::INTEGER AS dvce_screenheight,
        events.VALUE:dvce_screenwidth::INTEGER AS dvce_screenwidth,
        events.VALUE:event::STRING AS event,
        events.VALUE:event_fingerprint::STRING AS event_fingerprint,
        events.VALUE:event_format::STRING AS event_format,
        events.VALUE:event_id::STRING AS event_id,
        events.VALUE:event_name::STRING AS event_name,
        events.VALUE:event_vendor::STRING AS event_vendor,
        events.VALUE:event_version::STRING AS event_version,
        events.VALUE:refr_source::STRING AS referrer,
        events.VALUE:page_url::STRING AS page_url,
        events.VALUE:page_urlhost::STRING AS page_urlhost,
        events.VALUE:page_urlpath::STRING AS page_urlpath,
        events.VALUE:page_urlport::INTEGER AS page_urlport,
        events.VALUE:page_urlscheme::STRING AS page_urlscheme,
        events.VALUE:platform::STRING AS platform,
        events.VALUE:user_ipaddress::STRING AS user_ipaddress,
        events.VALUE:useragent::STRING AS useragent,
        events.VALUE:v_collector::STRING AS v_collector,
        events.VALUE:v_etl::STRING AS v_etl,
        events.VALUE:v_tracker::STRING AS v_tracker,
         --contexts_ai_spiny_author_1--
        initcap(replace(events.VALUE:contexts_ai_spiny_author_1[0]:authorName,''-'','' '')) as author,
        -- User contexts
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionDepth::INTEGER AS session_depth,
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionReferrer::STRING AS session_referrer,
        -- Location contexts
        events.VALUE:contexts_com_dbip_location_1[0]:city:names:en::STRING AS city,
        events.VALUE:contexts_com_dbip_location_1[0]:country:names:en::STRING AS country,
        events.VALUE:contexts_com_dbip_location_1[0]:subdivisions[0]:names:en::STRING AS subdivision_name,
        events.VALUE:contexts_com_dbip_location_1[0]:postal:code::STRING AS postal_code,
        -- ISP contexts
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:isp::STRING AS isp,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:organization::STRING AS organization,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:connection_type::STRING AS connection_type,
        -- User agent contexts
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:deviceFamily::STRING AS device_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osFamily::STRING AS os_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osVersion::STRING AS os_version,
        -- contexts_com_snowplowanalytics_snowplow_web_page_1
        events.VALUE:contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::STRING as snowplow_web_page_id,
        -- contexts_nl_basjes_yauaa_context_1--
        events.VALUE:contexts_nl_basjes_yauaa_context_1[0]:deviceClass:: VARCHAR AS device,
        -- bid
        ads.value:adNetworkId::STRING AS adNetworkId,
        ads.value:adServer::STRING AS adServer,
        ads.value:adSubType::STRING AS adSubType,              
        ads.value:adType::STRING AS adType,
        ads.value:adUnit::STRING AS adUnit,
        ads.value:adUnitPath::STRING AS ad_unit_path,
        ads.value:advertiserId::STRING AS advertiserId,       
        ads.value:campaignId::STRING AS campaignId,
        ads.value:cpm::FLOAT AS cpm,
        ads.value:creativeId::INTEGER AS creativeId,
        ads.value:lineItemId::STRING AS lineItemId,
        ads.value:location::STRING AS location,
        ads.value:rawAdNetworkId::INTEGER AS rawAdNetworkId,
        ------RENDERED--
        ads.value:renderedBid:adomains[0]::STRING AS rendered_adomains,
        ads.value:renderedBid:bidSource::STRING AS rendered_bidsource,
        ads.value:renderedBid:bidder::STRING AS rendered_bidder,
              ads.value:renderedBid:cpm::STRING AS rendered_cpm,
        ads.value:state::STRING AS state,
        CASE WHEN snowplow_web_page_id IS NOT NULL THEN 1 ELSE 0 END AS PAGE_VIEW_COUNT,
        CASE WHEN state IS NOT NULL THEN 1 ELSE 0 END AS IN_VIEW_IMPRESSION_COUNT
        
    FROM
        ALLCITYNETWORK_DEV.ENRICHED_RAW.ON3_BID_EVENTS_STREAM AS events,
        LATERAL FLATTEN(input => events.VALUE:unstruct_event_ai_spiny_ads_1:events) AS ads
)
SELECT * FROM flattened_data;

-- Insert into STG_AD_REQUEST_TEST
INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_REQUEST_TEST_METRIC (
	APP_ID,
	BR_COLORDEPTH,
	BR_COOKIES,
	BR_LANG,
	COLLECTOR_TSTAMP,
	DERIVED_TSTAMP,
	DOC_CHARSET,
	DOC_HEIGHT,
	DOC_WIDTH,
	DOMAIN_SESSIONID,
	DOMAIN_USERID,
	DVCE_CREATED_TSTAMP,
	DVCE_SCREENHEIGHT,
	DVCE_SCREENWIDTH,
	EVENT,
	EVENT_FINGERPRINT,
	EVENT_FORMAT,
	EVENT_ID,
	EVENT_NAME,
	EVENT_VENDOR,
	EVENT_VERSION,
	REFERRER,
	PAGE_URL,
	PAGE_URLHOST,
	PAGE_URLPATH,
	PAGE_URLPORT,
	PAGE_URLSCHEME,
	PLATFORM,
	USER_IPADDRESS,
	USERAGENT,
	V_COLLECTOR,
	V_ETL,
	V_TRACKER,
	SESSION_DEPTH,
	SESSION_REFERRER,
	CITY,
	COUNTRY,
	SUBDIVISION_NAME,
	POSTAL_CODE,
	AUTHOR,
	ISP,
	ORGANIZATION,
	CONNECTION_TYPE,
	SNOWPLOW_WEB_PAGE_ID,
	DEVICE,
	DEVICE_FAMILY,
	OS_FAMILY,
	OS_VERSION,
	AD_UNIT_PATH,
	ELEMENT_ID,
	OOP,
	SIZE_WIDTH,
	SIZE_HEIGHT,
	AD_UNIT_CODE,
	ADVERTISER_DOMAIN,
	AUCTION_ID,
	BID_SOURCE,
	BIDDER,
	CPM,
	CURRENCY,
	MEDIA_TYPE,
	NET_REVENUE,
	ORIGINAL_CPM,
	WINNING_SIZE_WIDTH,
	WINNING_SIZE_HEIGHT,
	STATUS_MESSAGE,
	TIME_TO_RESPOND,
	TTL,
    AD_REQUEST_COUNT
) 
WITH flattened_data AS (
    SELECT
        events.VALUE:app_id::STRING AS app_id,
        events.VALUE:br_colordepth::STRING AS br_colordepth,
        events.VALUE:br_cookies::BOOLEAN AS br_cookies,
        events.VALUE:br_lang::STRING AS br_lang,
        events.VALUE:collector_tstamp::TIMESTAMP AS collector_tstamp,
        events.VALUE:derived_tstamp::TIMESTAMP AS derived_tstamp,
        events.VALUE:doc_charset::STRING AS doc_charset,
        events.VALUE:doc_height::INTEGER AS doc_height,
        events.VALUE:doc_width::INTEGER AS doc_width,
        events.VALUE:domain_sessionid::STRING AS domain_sessionid,
        events.VALUE:domain_userid::STRING AS domain_userid,
        events.VALUE:dvce_created_tstamp::TIMESTAMP AS dvce_created_tstamp,
        events.VALUE:dvce_screenheight::INTEGER AS dvce_screenheight,
        events.VALUE:dvce_screenwidth::INTEGER AS dvce_screenwidth,
        events.VALUE:event::STRING AS event,
        events.VALUE:event_fingerprint::STRING AS event_fingerprint,
        events.VALUE:event_format::STRING AS event_format,
        events.VALUE:event_id::STRING AS event_id,
        events.VALUE:event_name::STRING AS event_name,
        events.VALUE:event_vendor::STRING AS event_vendor,
        events.VALUE:event_version::STRING AS event_version,
        events.VALUE:refr_source::STRING AS referrer,
        events.VALUE:page_url::STRING AS page_url,
        events.VALUE:page_urlhost::STRING AS page_urlhost,
        events.VALUE:page_urlpath::STRING AS page_urlpath,
        events.VALUE:page_urlport::INTEGER AS page_urlport,
        events.VALUE:page_urlscheme::STRING AS page_urlscheme,
        events.VALUE:platform::STRING AS platform,
        events.VALUE:user_ipaddress::STRING AS user_ipaddress,
        events.VALUE:useragent::STRING AS useragent,
        events.VALUE:v_collector::STRING AS v_collector,
        events.VALUE:v_etl::STRING AS v_etl,
        events.VALUE:v_tracker::STRING AS v_tracker,
        -- User contexts
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionDepth::INTEGER AS session_depth,
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionReferrer::STRING AS session_referrer,
        -- Location contexts
        events.VALUE:contexts_com_dbip_location_1[0]:city:names:en::STRING AS city,
        events.VALUE:contexts_com_dbip_location_1[0]:country:names:en::STRING AS country,
        events.VALUE:contexts_com_dbip_location_1[0]:subdivisions[0]:names:en::STRING AS subdivision_name,
        events.VALUE:contexts_com_dbip_location_1[0]:postal:code::STRING AS postal_code,
        --contexts_ai_spiny_author_1--
        initcap(replace(events.VALUE:contexts_ai_spiny_author_1[0]:authorName,''-'','' '')) as author,
        -- ISP contexts
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:isp::STRING AS isp,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:organization::STRING AS organization,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:connection_type::STRING AS connection_type,
        -- contexts_com_snowplowanalytics_snowplow_web_page_1
        events.VALUE:contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::STRING as snowplow_web_page_id,
        -- contexts_nl_basjes_yauaa_context_1--
        events.VALUE:contexts_nl_basjes_yauaa_context_1[0]:deviceClass:: VARCHAR AS device,
        -- User agent contexts
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:deviceFamily::STRING AS device_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osFamily::STRING AS os_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osVersion::STRING AS os_version,
        -- Ad requests
        ad_requests.value:adUnitPath::STRING AS ad_unit_path,
        ad_requests.value:elementId::STRING AS element_id,
        ad_requests.value:oop::BOOLEAN AS oop,
        ad_requests.value:sizes[0][0]::INTEGER AS size_width,
        ad_requests.value:sizes[0][1]::INTEGER AS size_height,
        -- Winning bids
        ad_requests.value:winningBids.prebid:adUnitCode::STRING AS ad_unit_code,
        ad_requests.value:winningBids.prebid:advertiserDomains[0]::STRING AS advertiser_domain,
        ad_requests.value:winningBids.prebid:auctionId::STRING AS auction_id,
        ad_requests.value:winningBids.prebid:bidSource::STRING AS bid_source,
        ad_requests.value:winningBids.prebid:bidder::STRING AS bidder,
        ad_requests.value:winningBids.prebid:cpm::FLOAT AS cpm,
        ad_requests.value:winningBids.prebid:currency::STRING AS currency,
        ad_requests.value:winningBids.prebid:mediaType::STRING AS media_type,
        ad_requests.value:winningBids.prebid:netRevenue::BOOLEAN AS net_revenue,
        ad_requests.value:winningBids.prebid:originalCpm::FLOAT AS original_cpm,
        ad_requests.value:winningBids.prebid:size[0]::INTEGER AS winning_size_width,
        ad_requests.value:winningBids.prebid:size[1]::INTEGER AS winning_size_height,
        ad_requests.value:winningBids.prebid:statusMessage::STRING AS status_message,
        ad_requests.value:winningBids.prebid:timeToRespond::INTEGER AS time_to_respond,
        ad_requests.value:winningBids.prebid:ttl::INTEGER AS ttl,
        CASE WHEN event_name = 'ad_request' and bidder IS NOT NULL THEN 1 ELSE 0 END AS ad_request_count,
    FROM
        ALLCITYNETWORK_DEV.ENRICHED_RAW.ON3_BID_EVENTS_STREAM AS events,
        LATERAL FLATTEN(input => events.VALUE:unstruct_event_ai_spiny_ad_request_1:events) AS ad_requests
)
SELECT * FROM flattened_data;


INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_REQUEST_TEST_METRIC(
	APP_ID,
	BR_COLORDEPTH,
	BR_COOKIES,
	BR_LANG,
	COLLECTOR_TSTAMP,
	DERIVED_TSTAMP,
	DOC_CHARSET,
	DOC_HEIGHT,
	DOC_WIDTH,
	DOMAIN_SESSIONID,
	DOMAIN_USERID,
	DVCE_CREATED_TSTAMP,
	DVCE_SCREENHEIGHT,
	DVCE_SCREENWIDTH,
	EVENT,
	EVENT_FINGERPRINT,
	EVENT_FORMAT,
	EVENT_ID,
	EVENT_NAME,
	EVENT_VENDOR,
	EVENT_VERSION,
	REFERRER,
	PAGE_URL,
	PAGE_URLHOST,
	PAGE_URLPATH,
	PAGE_URLPORT,
	PAGE_URLSCHEME,
	PLATFORM,
	USER_IPADDRESS,
	USERAGENT,
	V_COLLECTOR,
	V_ETL,
	V_TRACKER,
	AUTHOR,
	SESSION_DEPTH,
	SESSION_REFERRER,
	CITY,
	COUNTRY,
	SUBDIVISION_NAME,
	POSTAL_CODE,
	ISP,
	ORGANIZATION,
	CONNECTION_TYPE,
	SNOWPLOW_WEB_PAGE_ID,
	DEVICE,
	DEVICE_FAMILY,
	OS_FAMILY,
	OS_VERSION,
	ADUNITCODE,
	AD_UNIT_PATH,
	AUCTIONID,
	BIDSOURCE,
	BIDDER,
	BIDDERREQUESTID,
	ELEMENTID,
	GLOBALKEY,
	OOP,
	PREBIDSRC,
	SIZE_WIDTH,
	SIZE_HEIGHT,
	USERIDS,
    BID_REQUEST_COUNT
) 
WITH flattened_data AS (
    SELECT
        events.VALUE:app_id::STRING AS app_id,
        events.VALUE:br_colordepth::STRING AS br_colordepth,
        events.VALUE:br_cookies::BOOLEAN AS br_cookies,
        events.VALUE:br_lang::STRING AS br_lang,
        events.VALUE:collector_tstamp::TIMESTAMP AS collector_tstamp,
        events.VALUE:derived_tstamp::TIMESTAMP AS derived_tstamp,
        events.VALUE:doc_charset::STRING AS doc_charset,
        events.VALUE:doc_height::INTEGER AS doc_height,
        events.VALUE:doc_width::INTEGER AS doc_width,
        events.VALUE:domain_sessionid::STRING AS domain_sessionid,
        events.VALUE:domain_userid::STRING AS domain_userid,
        events.VALUE:dvce_created_tstamp::TIMESTAMP AS dvce_created_tstamp,
        events.VALUE:dvce_screenheight::INTEGER AS dvce_screenheight,
        events.VALUE:dvce_screenwidth::INTEGER AS dvce_screenwidth,
        events.VALUE:event::STRING AS event,
        events.VALUE:event_fingerprint::STRING AS event_fingerprint,
        events.VALUE:event_format::STRING AS event_format,
        events.VALUE:event_id::STRING AS event_id,
        events.VALUE:event_name::STRING AS event_name,
        events.VALUE:event_vendor::STRING AS event_vendor,
        events.VALUE:event_version::STRING AS event_version,
        events.VALUE:refr_source::STRING AS referrer,
        events.VALUE:page_url::STRING AS page_url,
        events.VALUE:page_urlhost::STRING AS page_urlhost,
        events.VALUE:page_urlpath::STRING AS page_urlpath,
        events.VALUE:page_urlport::INTEGER AS page_urlport,
        events.VALUE:page_urlscheme::STRING AS page_urlscheme,
        events.VALUE:platform::STRING AS platform,
        events.VALUE:user_ipaddress::STRING AS user_ipaddress,
        events.VALUE:useragent::STRING AS useragent,
        events.VALUE:v_collector::STRING AS v_collector,
        events.VALUE:v_etl::STRING AS v_etl,
        events.VALUE:v_tracker::STRING AS v_tracker,
         --contexts_ai_spiny_author_1--
        initcap(replace(events.VALUE:contexts_ai_spiny_author_1[0]:authorName,''-'','' '')) as author,
        -- User contexts
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionDepth::INTEGER AS session_depth,
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionReferrer::STRING AS session_referrer,
        -- Location contexts
        events.VALUE:contexts_com_dbip_location_1[0]:city:names:en::STRING AS city,
        events.VALUE:contexts_com_dbip_location_1[0]:country:names:en::STRING AS country,
        events.VALUE:contexts_com_dbip_location_1[0]:subdivisions[0]:names:en::STRING AS subdivision_name,
        events.VALUE:contexts_com_dbip_location_1[0]:postal:code::STRING AS postal_code,
        -- ISP contexts
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:isp::STRING AS isp,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:organization::STRING AS organization,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:connection_type::STRING AS connection_type,
        -- contexts_com_snowplowanalytics_snowplow_web_page_1
        events.VALUE:contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::STRING as snowplow_web_page_id,
        -- contexts_nl_basjes_yauaa_context_1--
        events.VALUE:contexts_nl_basjes_yauaa_context_1[0]:deviceClass:: VARCHAR AS device,
        -- User agent contexts
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:deviceFamily::STRING AS device_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osFamily::STRING AS os_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osVersion::STRING AS os_version,
        -- bid
        bid_request.value:adUnitCode::STRING AS adUnitCode,
        bid_request.value:adUnitPath::STRING AS ad_unit_path,
        bid_request.value:auctionId::STRING AS auctionId,       
        bid_request.value:bidSource::STRING AS bidSource,
        bid_request.value:bidder::STRING AS bidder,              
        bid_request.value:bidderRequestId::STRING AS bidderRequestId,
        bid_request.value:elementId::STRING AS elementId,
        bid_request.value:globalKey::STRING AS globalKey,
        bid_request.value:oop::BOOLEAN AS oop,
        bid_request.value:prebidSrc::STRING AS prebidSrc,
        bid_request.value:sizes[0][0]::INTEGER AS size_width,
        bid_request.value:sizes[0][1]::INTEGER AS size_height,
        bid_request.value:userIds::STRING AS userIds,
        CASE WHEN event_name = 'bid_request' THEN 1 ELSE 0 END AS bid_request_count
    FROM
       ALLCITYNETWORK_DEV.ENRICHED_RAW.ON3_BID_EVENTS_STREAM AS events,
        LATERAL FLATTEN(input => events.VALUE:unstruct_event_ai_spiny_bid_request_1:events) AS bid_request
)
SELECT * FROM flattened_data ;

-- Insert into STG_AD_RESPONSE_TEST
INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_RESPONSE_TEST_METRIC(
	APP_ID,
	BR_COLORDEPTH,
	BR_COOKIES,
	BR_LANG,
	COLLECTOR_TSTAMP,
	DERIVED_TSTAMP,
	DOC_CHARSET,
	DOC_HEIGHT,
	DOC_WIDTH,
	DOMAIN_SESSIONID,
	DOMAIN_USERID,
	DVCE_CREATED_TSTAMP,
	DVCE_SCREENHEIGHT,
	DVCE_SCREENWIDTH,
	EVENT,
	EVENT_FINGERPRINT,
	EVENT_FORMAT,
	EVENT_ID,
	EVENT_NAME,
	EVENT_VENDOR,
	EVENT_VERSION,
	REFERRER,
	PAGE_URL,
	PAGE_URLHOST,
	PAGE_URLPATH,
	PAGE_URLPORT,
	PAGE_URLSCHEME,
	PLATFORM,
	USER_IPADDRESS,
	USERAGENT,
	V_COLLECTOR,
	V_ETL,
	V_TRACKER,
	AUTHOR,
	SESSION_DEPTH,
	SESSION_REFERRER,
	CITY,
	COUNTRY,
	SUBDIVISION_NAME,
	POSTAL_CODE,
	ISP,
	ORGANIZATION,
	CONNECTION_TYPE,
	DEVICE_FAMILY,
	OS_FAMILY,
	OS_VERSION,
	SNOWPLOW_WEB_PAGE_ID,
	DEVICE,
	AD_UNIT_PATH,
	ADVERTISERID,
	CAMPAIGNID,
	ELEMENT_ID,
	ISBACKFILL,
	OOP,
	SIZE_WIDTH,
	SIZE_HEIGHT,
	SOURCEAGNOSTICCREATIVEID,
	SOURCEAGNOSTICLINEITEMID,
	RENDERED_AD_UNIT_CODE,
	RENDERED_ADVERTISERDOMAINS,
	RENDERED_AUCTIONID,
	RENDERED_BIDSOURCE,
	RENDERED_BIDDER,
	RENDERED_CPM,
	RENDERED_CURRENCY,
	RENDERED_GLOBALKEY,
	RENDERED_MEDIATYPE,
	RENDERED_NETREVENUE,
	RENDERED_ORIGINALCPM,
	RENDERED_STATUSMESSAGE,
	RENDERED_TIMETORESPOND,
	RENDERED_TTL,
	ISOBFUSCATED,
	OBFUSCATED_BIDDER,
	OBFUSCATED_CPM,
	AMAZON_WIDTH,
	AMAZON_LENGTH,
	AD_UNIT_CODE,
	ADVERTISER_DOMAIN,
	AUCTION_ID,
	BID_SOURCE,
	BIDDER,
	CPM,
	CURRENCY,
	MEDIA_TYPE,
	NET_REVENUE,
	ORIGINAL_CPM,
	WINNING_SIZE_WIDTH,
	WINNING_SIZE_HEIGHT,
	STATUS_MESSAGE,
	TIME_TO_RESPOND,
	TTL,
	YIELDGROUPIDS
) 
WITH flattened_data AS (
    SELECT
        events.VALUE:app_id::STRING AS app_id,
        events.VALUE:br_colordepth::STRING AS br_colordepth,
        events.VALUE:br_cookies::BOOLEAN AS br_cookies,
        events.VALUE:br_lang::STRING AS br_lang,       events.VALUE:collector_tstamp::TIMESTAMP AS collector_tstamp,
        events.VALUE:derived_tstamp::TIMESTAMP AS derived_tstamp,
        events.VALUE:doc_charset::STRING AS doc_charset,
        events.VALUE:doc_height::INTEGER AS doc_height,
        events.VALUE:doc_width::INTEGER AS doc_width,
        events.VALUE:domain_sessionid::STRING AS domain_sessionid,
        events.VALUE:domain_userid::STRING AS domain_userid,
        events.VALUE:dvce_created_tstamp::TIMESTAMP AS dvce_created_tstamp,
        events.VALUE:dvce_screenheight::INTEGER AS dvce_screenheight,
        events.VALUE:dvce_screenwidth::INTEGER AS dvce_screenwidth,
        events.VALUE:event::STRING AS event,
        events.VALUE:event_fingerprint::STRING AS event_fingerprint,
        events.VALUE:event_format::STRING AS event_format,
        events.VALUE:event_id::STRING AS event_id,
        events.VALUE:event_name::STRING AS event_name,
        events.VALUE:event_vendor::STRING AS event_vendor,
        events.VALUE:event_version::STRING AS event_version,
        events.VALUE:refr_source::STRING AS referrer,
        events.VALUE:page_url::STRING AS page_url,
        events.VALUE:page_urlhost::STRING AS page_urlhost,
        events.VALUE:page_urlpath::STRING AS page_urlpath,
        events.VALUE:page_urlport::INTEGER AS page_urlport,
        events.VALUE:page_urlscheme::STRING AS page_urlscheme,
        events.VALUE:platform::STRING AS platform,
        events.VALUE:user_ipaddress::STRING AS user_ipaddress,
        events.VALUE:useragent::STRING AS useragent,
        events.VALUE:v_collector::STRING AS v_collector,
        events.VALUE:v_etl::STRING AS v_etl,
        events.VALUE:v_tracker::STRING AS v_tracker,
         --contexts_ai_spiny_author_1--
        initcap(replace(events.VALUE:contexts_ai_spiny_author_1[0]:authorName,''-'','' '')) as author,
        -- User contexts
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionDepth::INTEGER AS session_depth,
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionReferrer::STRING AS session_referrer,
        -- Location contexts
        events.VALUE:contexts_com_dbip_location_1[0]:city:names:en::STRING AS city,
        events.VALUE:contexts_com_dbip_location_1[0]:country:names:en::STRING AS country,
        events.VALUE:contexts_com_dbip_location_1[0]:subdivisions[0]:names:en::STRING AS subdivision_name,
        events.VALUE:contexts_com_dbip_location_1[0]:postal:code::STRING AS postal_code,
        -- ISP contexts
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:isp::STRING AS isp,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:organization::STRING AS organization,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:connection_type::STRING AS connection_type,
        -- User agent contexts
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:deviceFamily::STRING AS device_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osFamily::STRING AS os_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osVersion::STRING AS os_version,
         -- contexts_com_snowplowanalytics_snowplow_web_page_1
        events.VALUE:contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::STRING as snowplow_web_page_id,
        -- contexts_nl_basjes_yauaa_context_1--
        events.VALUE:contexts_nl_basjes_yauaa_context_1[0]:deviceClass:: VARCHAR AS device,
        -- Ad requests
        ad_response.value:adUnitPath::STRING AS ad_unit_path,
        ad_response.value:advertiserId::STRING AS advertiserId,
        ad_response.value:campaignId::STRING AS campaignId,
        ad_response.value:elementId::STRING AS element_id,
        ad_response.value:isBackfill::BOOLEAN AS isBackfill,
        ad_response.value:oop::BOOLEAN AS oop,
        ad_response.value:sizes[0][0]::INTEGER AS size_width,
        ad_response.value:sizes[0][1]::INTEGER AS size_height,
        ad_response.value:sourceAgnosticCreativeId::STRING AS sourceAgnosticCreativeId,
        ad_response.value:sourceAgnosticLineItemId::STRING AS sourceAgnosticLineItemId,
        -- Rendered 
ad_response.value:renderedBid:adUnitCode::STRING AS rendered_ad_unit_code,
ad_response.value:renderedBid:advertiserDomains[0]::STRING AS rendered_advertiserDomains,
ad_response.value:renderedBid:auctionId::STRING AS rendered_auctionId,
ad_response.value:renderedBid:bidSource::STRING AS rendered_bidsource,
ad_response.value:renderedBid:bidder::STRING AS rendered_bidder,
ad_response.value:renderedBid:cpm::FLOAT AS rendered_cpm,
ad_response.value:renderedBid:currency::STRING AS rendered_currency,
ad_response.value:renderedBid:globalKey::STRING AS rendered_globalKey,
ad_response.value:renderedBid:mediaType::STRING AS rendered_mediaType,
ad_response.value:renderedBid:netRevenue::BOOLEAN AS rendered_netRevenue,
ad_response.value:renderedBid:originalCpm::FLOAT AS rendered_originalCpm,
ad_response.value:renderedBid:statusMessage::STRING AS rendered_statusMessage,
ad_response.value:renderedBid:timeToRespond::STRING AS rendered_timeToRespond,
ad_response.value:renderedBid:ttl::INTEGER AS rendered_ttl,
        -- Winning bids
ad_response.value:winningBids.amazon:isObfuscated::STRING AS isObfuscated,

ad_response.value:winningBids.amazon.obfuscated:bidder::STRING AS Obfuscated_bidder,

ad_response.value:winningBids.amazon.obfuscated:cpm::STRING AS Obfuscated_cpm,

ad_response.value:winningBids.amazon:size[0]::STRING AS amazon_width,

ad_response.value:winningBids.amazon:size[1]::STRING AS amazon_length,

ad_response.value:winningBids.prebid:adUnitCode::STRING AS ad_unit_code,
        ad_response.value:winningBids.prebid:advertiserDomains[0]::STRING AS advertiser_domain,
        ad_response.value:winningBids.prebid:auctionId::STRING AS auction_id,
        ad_response.value:winningBids.prebid:bidSource::STRING AS bid_source,
        ad_response.value:winningBids.prebid:bidder::STRING AS bidder,
        ad_response.value:winningBids.prebid:cpm::FLOAT AS cpm,
        ad_response.value:winningBids.prebid:currency::STRING AS currency,
        ad_response.value:winningBids.prebid:mediaType::STRING AS media_type,
        ad_response.value:winningBids.prebid:netRevenue::BOOLEAN AS net_revenue,
        ad_response.value:winningBids.prebid:originalCpm::FLOAT AS original_cpm,
        ad_response.value:winningBids.prebid:size[0]::INTEGER AS winning_size_width,
        ad_response.value:winningBids.prebid:size[1]::INTEGER AS winning_size_height,
        ad_response.value:winningBids.prebid:statusMessage::STRING AS status_message,
        ad_response.value:winningBids.prebid:timeToRespond::INTEGER AS time_to_respond,
        ad_response.value:winningBids.prebid:ttl::INTEGER AS ttl,
        ad_response.value:yieldGroupIds[0]::STRING AS yieldGroupIds
    FROM
        ALLCITYNETWORK_DEV.ENRICHED_RAW.ON3_BID_EVENTS_STREAM AS events,
        LATERAL FLATTEN(input => events.VALUE:unstruct_event_ai_spiny_ad_response_1:events) AS ad_response
)
SELECT * FROM flattened_data;

-- Insert into STG_BID_RESPONSE_TEST

INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_RESPONSE_TEST_METRIC(
	APP_ID,
	BR_COLORDEPTH,
	BR_COOKIES,
	BR_LANG,
	COLLECTOR_TSTAMP,
	DERIVED_TSTAMP,
	DOC_CHARSET,
	DOC_HEIGHT,
	DOC_WIDTH,
	DOMAIN_SESSIONID,
	DOMAIN_USERID,
	DVCE_CREATED_TSTAMP,
	DVCE_SCREENHEIGHT,
	DVCE_SCREENWIDTH,
	EVENT,
	EVENT_FINGERPRINT,
	EVENT_FORMAT,
	EVENT_ID,
	EVENT_NAME,
	EVENT_VENDOR,
	EVENT_VERSION,
	REFERRER,
	PAGE_URL,
	PAGE_URLHOST,
	PAGE_URLPATH,
	PAGE_URLPORT,
	PAGE_URLSCHEME,
	PLATFORM,
	USER_IPADDRESS,
	USERAGENT,
	V_COLLECTOR,
	V_ETL,
	V_TRACKER,
	AUTHOR,
	SESSION_DEPTH,
	SESSION_REFERRER,
	CITY,
	COUNTRY,
	SUBDIVISION_NAME,
	POSTAL_CODE,
	ISP,
	ORGANIZATION,
	CONNECTION_TYPE,
	SNOWPLOW_WEB_PAGE_ID,
	DEVICE,
	DEVICE_FAMILY,
	OS_FAMILY,
	OS_VERSION,
	ADUNITCODE,
	AD_UNIT_PATH,
	AUCTION_ID,
	ADVERTISERDOMAINS,
	AUCTIONSTATUS,
	BID_SOURCE,
	BIDDER,
	BIDDERREQUESTID,
	CPM,
	CURRENCY,
	ELEMENTID,
	GLOBALKEY,
	OOP,
	ORIGINALCPM,
	STATUS_MESSAGE,
	TIME_TO_RESPOND,
	TTL,
	USERIDS,
    no_bid_count,
    bid_response,
    cancelled_bids_count,
    timed_out_bids_count
)
WITH flattened_data AS (
    SELECT
        events.VALUE:app_id::STRING AS app_id,
        events.VALUE:br_colordepth::STRING AS br_colordepth,
        events.VALUE:br_cookies::BOOLEAN AS br_cookies,
        events.VALUE:br_lang::STRING AS br_lang,
        events.VALUE:collector_tstamp::TIMESTAMP AS collector_tstamp,
        events.VALUE:derived_tstamp::TIMESTAMP AS derived_tstamp,
        events.VALUE:doc_charset::STRING AS doc_charset,
        events.VALUE:doc_height::INTEGER AS doc_height,
        events.VALUE:doc_width::INTEGER AS doc_width,
        events.VALUE:domain_sessionid::STRING AS domain_sessionid,
        events.VALUE:domain_userid::STRING AS domain_userid,
        events.VALUE:dvce_created_tstamp::TIMESTAMP AS dvce_created_tstamp,
        events.VALUE:dvce_screenheight::INTEGER AS dvce_screenheight,
        events.VALUE:dvce_screenwidth::INTEGER AS dvce_screenwidth,
        events.VALUE:event::STRING AS event,
        events.VALUE:event_fingerprint::STRING AS event_fingerprint,
        events.VALUE:event_format::STRING AS event_format,
        events.VALUE:event_id::STRING AS event_id,
        events.VALUE:event_name::STRING AS event_name,
        events.VALUE:event_vendor::STRING AS event_vendor,
        events.VALUE:event_version::STRING AS event_version,
        events.VALUE:refr_source::STRING AS referrer,
        events.VALUE:page_url::STRING AS page_url,
        events.VALUE:page_urlhost::STRING AS page_urlhost,
        events.VALUE:page_urlpath::STRING AS page_urlpath,
        events.VALUE:page_urlport::INTEGER AS page_urlport,
        events.VALUE:page_urlscheme::STRING AS page_urlscheme,
        events.VALUE:platform::STRING AS platform,
        events.VALUE:user_ipaddress::STRING AS user_ipaddress,
        events.VALUE:useragent::STRING AS useragent,
        events.VALUE:v_collector::STRING AS v_collector,
        events.VALUE:v_etl::STRING AS v_etl,
        events.VALUE:v_tracker::STRING AS v_tracker,
         --contexts_ai_spiny_author_1--
        initcap(replace(events.VALUE:contexts_ai_spiny_author_1[0]:authorName,''-'','' '')) as author,
        -- User contexts
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionDepth::INTEGER AS session_depth,
        events.VALUE:contexts_ai_spiny_user_1[0]:sessionReferrer::STRING AS session_referrer,
        -- Location contexts
        events.VALUE:contexts_com_dbip_location_1[0]:city:names:en::STRING AS city,
        events.VALUE:contexts_com_dbip_location_1[0]:country:names:en::STRING AS country,
        events.VALUE:contexts_com_dbip_location_1[0]:subdivisions[0]:names:en::STRING AS subdivision_name,
        events.VALUE:contexts_com_dbip_location_1[0]:postal:code::STRING AS postal_code,
        -- ISP contexts
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:isp::STRING AS isp,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:organization::STRING AS organization,
        events.VALUE:contexts_com_dbip_isp_1[0]:traits:connection_type::STRING AS connection_type,
        -- contexts_com_snowplowanalytics_snowplow_web_page_1
        events.VALUE:contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::STRING as snowplow_web_page_id,
        -- contexts_nl_basjes_yauaa_context_1--
        events.VALUE:contexts_nl_basjes_yauaa_context_1[0]:deviceClass:: VARCHAR AS device,
        -- User agent contexts
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:deviceFamily::STRING AS device_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osFamily::STRING AS os_family,
        events.VALUE:contexts_com_snowplowanalytics_snowplow_ua_parser_context_1[0]:osVersion::STRING AS os_version,
        -- Ad requests
        bid_response.value:adUnitCode::STRING AS adUnitCode,
        bid_response.value:adUnitPath::STRING AS ad_unit_path,
        bid_response.value:auctionId::STRING AS auction_id,       
        bid_response.value:advertiserDomains[0]::STRING AS advertiserDomains,
        bid_response.value:auctionStatus::STRING AS auctionStatus,
        bid_response.value:bidSource::STRING AS bid_source,
        bid_response.value:bidder::STRING AS bidder,              
        bid_response.value:bidderRequestId::STRING AS bidderRequestId,
        bid_response.value:cpm:: FLOAT AS cpm,
        bid_response.value:currency:: STRING AS currency,
        bid_response.value:elementId:: STRING AS elementId,
        bid_response.value:globalKey::STRING AS globalKey,
        bid_response.value:oop::BOOLEAN AS oop,
        bid_response.value:originalCpm::STRING AS originalCpm,
        bid_response.value:statusMessage::STRING AS status_message,
        bid_response.value:timeToRespond::INTEGER AS time_to_respond,
        bid_response.value:ttl::INTEGER AS ttl,
        bid_response.value:userIds::STRING AS userIds,
        CASE WHEN auctionStatus = 'no-bid' THEN 1 ELSE 0 END AS no_bid_count,
        1 AS bid_response,
        CASE WHEN auctionStatus = 'error' THEN 1 ELSE 0 END AS cancelled_bids_count,
        CASE WHEN auctionStatus = 'timeout' THEN 1 ELSE 0 END AS timed_out_bids_count
    FROM
        ALLCITYNETWORK_DEV.ENRICHED_RAW.ON3_BID_EVENTS_STREAM AS events,
        LATERAL FLATTEN(input => events.VALUE:unstruct_event_ai_spiny_bid_response_1:events) AS bid_response
)
SELECT * FROM flattened_data;

COMMIT;
RETURN '' TABLES POPULATED SUCCESSFULY'';
END;
';



CREATE OR REPLACE PROCEDURE ALLCITYNETWORK_DEV.ON3_KIPI.POPULATE_COMBINED_TABLE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
-- INSERT INTO ONE TABLE FROM BASE 5 --
INSERT INTO ALLCITYNETWORK_DEV.ON3_KIPI.COMBINED_BID_METRIC (
        DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
        organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
)
WITH bid_responses AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ADUNITCODE as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        null as state,
        null as rendered_bidder,
        ttl,
        sum(NO_BID_COUNT) as NO_BID,
        sum(BID_RESPONSE) as BID_RESPONSE,
        sum(CANCELLED_BIDS_COUNT) as CANCELLED_BIDS,
        sum(TIMED_OUT_BIDS_COUNT) as TIMED_OUT_BIDS,
        null as BID_REQUEST,    
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST,
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_RESPONSE_TEST_STR
    GROUP BY DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
bid_requests AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bidsource as bid_source,
        author,
        referrer,
        null as time_to_respond,
        null as state,
        null as cpm,
        null as rendered_bidder,
        null as ttl,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        sum(BID_REQUEST_COUNT) as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_BID_REQUEST_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunitcode,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ads AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunit as ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        author,
        referrer,
        cpm,
        rendered_bidder,
        null as time_to_respond,
        null as bidder,
        null as bid_source,
        null as ttl,
        state,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        sum(PAGE_VIEW_COUNT) as PAGE_VIEW,
        sum(IN_VIEW_IMPRESSION_COUNT) as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_ADS_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        adunit,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ad_response AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        ttl,
        time_to_respond,
        null as state,
        cpm,
        rendered_bidder,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        null as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_RESPONSE_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
),
ad_request AS (
    SELECT
        LEFT(DERIVED_TSTAMP,10) AS DERIVED_TSTAMP,
        LEFT(COLLECTOR_TSTAMP,10) AS COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_family AS device_name,
        os_family AS operating_system_name,
        os_version AS operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        cpm,
        time_to_respond,
        null as rendered_bidder,
        null as state,
        ttl,
        null as NO_BID,
        null as BID_RESPONSE,
        null as CANCELLED_BIDS ,
        null as TIMED_OUT_BIDS ,
        null as BID_REQUEST,
        null as PAGE_VIEW,
        null as IN_VIEW_IMPRESSION,
        sum(AD_REQUEST_COUNT) as AD_REQUEST
    FROM ALLCITYNETWORK_DEV.ON3_KIPI.STG_AD_REQUEST_TEST_STR
    GROUP BY DERIVED_TSTAMP,
    COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl
)
SELECT DERIVED_TSTAMP,
        COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM bid_responses
UNION ALL
SELECT DERIVED_TSTAMP,
 COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM bid_requests
UNION ALL
SELECT DERIVED_TSTAMP,
COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ads
UNION ALL
SELECT DERIVED_TSTAMP,
COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
        device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ad_response
UNION ALL
SELECT DERIVED_TSTAMP,
 COLLECTOR_TSTAMP,
        event_name,
        platform,
        country,
         organization,
        ad_unit_code,
        connection_type,
        device,
       device_name ,
        operating_system_name ,
        operating_system_name_version,
        bidder,
        bid_source,
        author,
        referrer,
        time_to_respond,
        cpm,
        state,
        rendered_bidder,
        ttl,
        NO_BID,
        BID_RESPONSE,
        CANCELLED_BIDS ,
        TIMED_OUT_BIDS ,
        BID_REQUEST,
        PAGE_VIEW,
        IN_VIEW_IMPRESSION,
        AD_REQUEST
FROM ad_request;
RETURN '' TABLE POPULATED SUCCESSFULY'';
END;

';
